#
# Makefile for the linux ext2-filesystem routines.
#

#O_TARGET := lpfs.o

#obj-y    := balloc.o bitmap.o dir.o file.o fsync.o ialloc.o inode.o \
		ioctl.o namei.o super.o symlink.o
#obj-m    := $(O_TARGET)

#include $(TOPDIR)/Rules.make

obj-$(CONFIG_LPFS) += lpfs.o

lpfs-y := balloc.o bitmap.o dir.o file.o fsync.o ialloc.o inode.o \
		ioctl.o namei.o super.o symlink.o

